from modules.MCVariable import MCVariable as MCV
from modules.MCVariable import Variable as Var

GeVc2="[GeV/c^{2}]"
GeV  ="[GeV]"
MeV  ="[MeV]"

def mc_variables() :
    b=base_variables()
    m={
            # inputs
            "m0"           : MCV( b["m0"],            index_offset=1 ),
            "m12"          : MCV( b["m0"],            index_offset=2 ),
            "A0"           : MCV( b["A0"],            index_offset=3 ),
            "tanb"         : MCV( b["tanb"],          index_offset=4 ),
            "mtop"         : MCV( b["mtop"],          index_offset=6 ),
            "MZ"           : MCV( b["MZ"],            index_offset=7 ),
            "GZ_in"        : MCV( b["GZ_in"],         index_offset=8 ),
            "DAlpha_had"   : MCV( b["DAlpha_had"],    index_offset=9 ),
            # predictions
            "R(b->sg)"     : MCV( b["R(b->sg)"],      index_offset=0,  offset_relative_to="PredictionIndex" ),
            "R(D_ms)"      : MCV( b["R(D_ms)"],       index_offset=1,  offset_relative_to="PredictionIndex" ),
            "Bsmumu"       : MCV( b["Bsmumu"],        index_offset=2,  offset_relative_to="PredictionIndex" ),
            "R(B->taunu)"  : MCV( b["R(B->taunu)"],   index_offset=3,  offset_relative_to="PredictionIndex" ),
            "R(B->Xsll)"   : MCV( b["R(B->Xsll)"],    index_offset=4,  offset_relative_to="PredictionIndex" ),
            "R(K->lnu)"    : MCV( b["R(K->lnu)"],     index_offset=5,  offset_relative_to="PredictionIndex" ),
            "Delta(g-2)"   : MCV( b["Delta(g-2)"],    index_offset=6,  offset_relative_to="PredictionIndex" ),
            "MW"           : MCV( b["MW"],            index_offset=7,  offset_relative_to="PredictionIndex" ),
            "sintheta_eff" : MCV( b["sintheta_eff"],  index_offset=8,  offset_relative_to="PredictionIndex" ),
            "Gamma_Z"      : MCV( b["Gamma_Z"],       index_offset=9,  offset_relative_to="PredictionIndex" ),
            "Rl"           : MCV( b["Rl"],            index_offset=10, offset_relative_to="PredictionIndex" ),
            "Rb"           : MCV( b["Rb"],            index_offset=11, offset_relative_to="PredictionIndex" ),
            "Rc"           : MCV( b["Rc"],            index_offset=12, offset_relative_to="PredictionIndex" ),
            "Afb(b)"       : MCV( b["Afb(b)"],        index_offset=13, offset_relative_to="PredictionIndex" ),
            "Afb(c)"       : MCV( b["Afb(c)"],        index_offset=14, offset_relative_to="PredictionIndex" ),
            "Ab16"         : MCV( b["Ab16"],          index_offset=15, offset_relative_to="PredictionIndex" ),
            "Ac17"         : MCV( b["Ac17"],          index_offset=16, offset_relative_to="PredictionIndex" ),
            "Al(SLD)"      : MCV( b["Al(SLD)"],       index_offset=17, offset_relative_to="PredictionIndex" ),
            "m_h^0"        : MCV( b["m_h^0"],         index_offset=18, offset_relative_to="PredictionIndex" ),
            "Oh^2"         : MCV( b["Oh^2"],          index_offset=19, offset_relative_to="PredictionIndex" ),
            "Al(P_tau)"    : MCV( b["Al(P_tau)"],     index_offset=20, offset_relative_to="PredictionIndex" ),
            "Al_fb"        : MCV( b["Al_fb"],         index_offset=21, offset_relative_to="PredictionIndex" ),
            "sigma_had^0"  : MCV( b["sigma_had^0"],   index_offset=22, offset_relative_to="PredictionIndex" ),
            "R(Delta_md)"  : MCV( b["R(Delta_md)"],   index_offset=23, offset_relative_to="PredictionIndex" ),
            "R(Delta_mk)"  : MCV( b["R(Delta_mk)"],   index_offset=24, offset_relative_to="PredictionIndex" ),
            "R(Kp->pinn)"  : MCV( b["R(Kp->pinn)"],   index_offset=25, offset_relative_to="PredictionIndex" ),
            "BR(Bd->ll)"   : MCV( b["BR(Bd->ll)"],    index_offset=26, offset_relative_to="PredictionIndex" ),
            "R(Dms)/R(Dmd)": MCV( b["R(Dms)/R(Dmd)"], index_offset=27, offset_relative_to="PredictionIndex" ),
            "D_0(K*g)"     : MCV( b["D_0(K*g)"],      index_offset=28, offset_relative_to="PredictionIndex" ),
            "BR(b->sg)"    : MCV( b["BR(b->sg)"],     index_offset=29, offset_relative_to="PredictionIndex" ),
            "sigma_pp^SI"  : MCV( b["sigma_pp^SI"],   index_offset=33, offset_relative_to="PredictionIndex" ),
            # Spectrum
            "chi1"         : MCV( b["chi1"],          index_offset=0,  offset_relative_to="SpectrumIndex" ),
            "chi2"         : MCV( b["chi2"],          index_offset=1,  offset_relative_to="SpectrumIndex" ),
            "neu1"         : MCV( b["neu1"],          index_offset=2,  offset_relative_to="SpectrumIndex" ),
            "neu2"         : MCV( b["neu2"],          index_offset=3,  offset_relative_to="SpectrumIndex" ),
            "neu3"         : MCV( b["neu3"],          index_offset=4,  offset_relative_to="SpectrumIndex" ),
            "neu4"         : MCV( b["neu4"],          index_offset=5,  offset_relative_to="SpectrumIndex" ),
            "sel_r"        : MCV( b["sel_r"],         index_offset=6,  offset_relative_to="SpectrumIndex" ),
            "sel_l"        : MCV( b["sel_l"],         index_offset=7,  offset_relative_to="SpectrumIndex" ),
            "snu_e"        : MCV( b["snu_e"],         index_offset=8,  offset_relative_to="SpectrumIndex" ),
            "smu_r"        : MCV( b["smu_r"],         index_offset=9,  offset_relative_to="SpectrumIndex" ),
            "smu_l"        : MCV( b["smu_l"],         index_offset=10, offset_relative_to="SpectrumIndex" ),
            "snu_mu"       : MCV( b["snu_mu"],        index_offset=11, offset_relative_to="SpectrumIndex" ),
            "stau_1"       : MCV( b["stau_1"],        index_offset=12, offset_relative_to="SpectrumIndex" ),
            "stau_2"       : MCV( b["stau_2"],        index_offset=13, offset_relative_to="SpectrumIndex" ),
            "snu_tau"      : MCV( b["snu_tau"],       index_offset=14, offset_relative_to="SpectrumIndex" ),
            "squark_r"     : MCV( b["squark_r"],      index_offset=15, offset_relative_to="SpectrumIndex" ),
            "squark_l"     : MCV( b["squark_l"],      index_offset=16, offset_relative_to="SpectrumIndex" ),
            "stop1"        : MCV( b["stop1"],         index_offset=17, offset_relative_to="SpectrumIndex" ),
            "stop2"        : MCV( b["stop2"],         index_offset=18, offset_relative_to="SpectrumIndex" ),
            "sbottom1"     : MCV( b["sbottom1"],      index_offset=19, offset_relative_to="SpectrumIndex" ),
            "sbottom2"     : MCV( b["sbottom2"],      index_offset=20, offset_relative_to="SpectrumIndex" ),
            "gluino"       : MCV( b["gluino"],        index_offset=21, offset_relative_to="SpectrumIndex" ),
            "mh0"          : MCV( b["mh0"],           index_offset=22, offset_relative_to="SpectrumIndex" ),
            "mH0"          : MCV( b["mH0"],           index_offset=23, offset_relative_to="SpectrumIndex" ),
            "mA0"          : MCV( b["mA0"],           index_offset=24, offset_relative_to="SpectrumIndex" ),
            "mH+-"         : MCV( b["mH+-"],          index_offset=25, offset_relative_to="SpectrumIndex" ),
    }
    return m

def base_variables() :
    return {
        "m0"           : Var( "m0",            r"$m_{0} %s$"%GeVc2 ),
        "m12"          : Var( "m0",            r"$m_{0} %s$"%GeVc2 ),
        "A0"           : Var( "A0",            r"$A_{0} %s$"%GeV ),
        "tanb"         : Var( "tanb",          r"$\tan(\beta)$" ),
        "mtop"         : Var( "mtop",          r"$m_{t} %s$"%GeVc2,                    "GAUSS", 173.2,    [0.9]  ),
        "MZ"           : Var( "MZ",            r"$m_{Z} %s$"%GeVc2,                    "GAUSS", 91.1875,  [0.0021] ),
        "GZ_in"        : Var( "GZ_in",         r"$\Gamma_{Z} %s (input)"%GeV,          "GAUSS", 2.4952,   [0.0023] ),
        "DAlpha_had"   : Var( "DAlpha_had",    r"$\Delta\alpha_{had}$",                "GAUSS", 0.027490, [0.0001] ),
        "R(b->sg)"     : Var( "R(b->sg)",      r"$R(b\rightarrow s\gamma)$",           "GAUSS", 1.117,    [0.12] ),
        "R(D_ms)"      : Var( "R(D_ms)",       r"$R(\Delta_{ms}$",                     "GAUSS", 0.97,     [0.01, 0.27] ),
        "Bsmumu"       : Var( "Bsmumu",        r"$BR(B_{s}\rightarrow\mu^{+}\mu^{-})", "UL",    4.6E-8,   [0.1E-9, 0.2E-9] ),
        "R(B->taunu)"  : Var( "R(B->taunu)",   r"$R(B\rightarrow\tau\nu)$",            "GAUSS", 1.43,     [0.43] ),
        "R(B->Xsll)"   : Var( "R(B->Xsll)",    r"$R(B\rightarrow X_{s}\ell\ell$",      "GAUSS", 0.99,     [0.32, 0.00] ),
        "R(K->lnu)"    : Var( "R(K->lnu)",     r"$R(K\rightarrow\ell\nu)$",            "GAUSS", 1.008,    [0.014 ] ),
        "Delta(g-2)"   : Var( "Delta(g-2)",    r"$\Delta(g-2)_{\mu}$",                 "GAUSS", 30.2E-10, [8.8E-10, 2.0E-10] ),
        "MW"           : Var( "MW",            r"$m_{W} %s$"%GeVc2,                    "GAUSS", 80.399,   [0.023, 0.01] ),
        "sintheta_eff" : Var( "sintheta_eff",  r"$\sin(\theta_{eff}) (Q_{fb})$",       "GAUSS", 0.2324,   [0.0012] ),
        "Gamma_Z"      : Var( "Gamma_Z",       r"$\Gamma_{Z} %s"%MeV,                  "GAUSS", 2495.2,   [2.3, 1.0] ),
        "Rl"           : Var( "Rl",            r"$R_{\ell}$",                          "GAUSS", 20.767,   [0.025] ),
        "Rb"           : Var( "Rb",            r"$R_{b}$",                             "GAUSS", 0.21629,  [0.00066] ),
        "Rc"           : Var( "Rc",            r"$R_{c}$",                             "GAUSS", 0.1721,   [0.00066] ),
        "Afb(b)"       : Var( "Afb(b)",        r"$A_{fb}(b)$",                         "GAUSS", 0.0992,   [0.0016] ),
        "Afb(c)"       : Var( "Afb(c)",        r"$A_{fb}(c)$",                         "GAUSS", 0.0707,   [0.0035] ),
        "Ab16"         : Var( "Ab16",          r"$A_{b}$",                             "GAUSS", 0.923,    [0.020] ),
        "Ac17"         : Var( "Ac17",          r"$A_{c}$",                             "GAUSS", 0.670,    [0.027] ),
        "Al(SLD)"      : Var( "Al(SLD)",       r"$A_{\ell} (SLD)$",                    "GAUSS", 0.1513,   [0.0021] ),
        "m_h^0"        : Var( "m_h^0",         r"$M_{h^{0}} [GeV/c^{2}]$",             "LL",    115.0,    [1.1, 1.5] ),
        "Oh^2"         : Var( "Oh^2",          r"$\Omega h^{2}$",                      "GAUSS", 0.1109,   [0.0056, 0.012] ),
        "Al(P_tau)"    : Var( "Al(P_tau)",     r"$A\ell (P_{\tau})$",                  "GAUSS", 0.1465,   [0.0032] ),
        "Al_fb"        : Var( "Al_fb",         r"$A\ell FB$",                          "GAUSS", 0.01714,  [0.00095] ),
        "sigma_had^0"  : Var( "sigma_had^0",   r"$\sigma_{had}^{0} (nb)$",             "GAUSS", 41.540,   [0.037] ),
        "R(Delta_md)"  : Var( "R(Delta_md)",   r"$R(\Delta_{md})$",                    "GAUSS", 1.05,     [0.01, 0.34] ),
        "R(Delta_mk)"  : Var( "R(Delta_mk)",   r"$R(\Delta_{mk})$",                    "GAUSS", 1.08,     [0.00, 0.14] ),
        "R(Kp->pinn)"  : Var( "R(Kp->pinn)",   r"$R(K\pi\rightarrow\pi nn)$",          "UL",    4.5,      [0.01] ),
        "BR(Bd->ll)"   : Var( "BR(Bd->ll)",    r"$BR(B_{d}\rightarrow\ell\ell$",       "UL",    2.3E-8,   [0.0, 0.2E-9] ),
        "R(Dms)/R(Dmd)": Var( "R(Dms)/R(Dmd)", r"$R(\Delta_{ms})/R(\Delta_{md})$",     "GAUSS", 1.00,     [0.01, 0.13] ),
        "D_0(K*g)"     : Var( "D_0(K*g)",      r"$\Delta_{0}(K^{*}\gamma$",            "GAUSS", 0.028,    [0.023, 0.024] ),
        "BR(b->sg)"    : Var( "BR(b->sg)",     r"$BR(b\rightarrow s\gamma)$",          "GAUSS", 1.117,    [0.12] ),
        "sigma_pp^SI"  : Var( "sigma_pp^SI",   r"$\sigma_{p}^{SI}$" ),
        "chi1"         : Var( "chi1",          r"$m_{\tilde{\chi}^{\pm}_{1}} %s$"%GeVc2 ),
        "chi2"         : Var( "chi2",          r"$m_{\tilde{\chi}^{\pm}_{2}} %s$"%GeVc2 ),
        "neu1"         : Var( "neu1",          r"$m_{\tilde{\chi}^{0}_{1}} %s$"%GeVc2 ),
        "neu2"         : Var( "neu2",          r"$m_{\tilde{\chi}^{0}_{2}} %s$"%GeVc2 ),
        "neu3"         : Var( "neu3",          r"$m_{\tilde{\chi}^{0}_{3}} %s$"%GeVc2 ),
        "neu4"         : Var( "neu4",          r"$m_{\tilde{\chi}^{0}_{4}} %s$"%GeVc2 ),
        "sel_r"        : Var( "sel_r",         r"$m_{\tilde{e}_{r}} %s$"%GeVc2 ),
        "sel_l"        : Var( "sel_l",         r"$m_{\tilde{e}_{l}} %s$"%GeVc2 ),
        "snu_e"        : Var( "snu_e",         r"$m_{\tilde{\nu}_{e}} %s$"%GeVc2 ),
        "smu_r"        : Var( "smu_r",         r"$m_{\tilde{\mu}_{r}} %s$"%GeVc2 ),
        "smu_l"        : Var( "smu_l",         r"$m_{\tilde{\mu}_{l}} %s$"%GeVc2 ),
        "snu_mu"       : Var( "snu_mu",        r"$m_{\tilde{\nu}_{\mu}} %s$"%GeVc2 ),
        "stau_1"       : Var( "stau_1",        r"$m_{\tilde{\tau}_{1}} %s$"%GeVc2 ),
        "stau_2"       : Var( "stau_2",        r"$m_{\tilde{\tau}_{2}} %s$"%GeVc2 ),
        "snu_tau"      : Var( "snu_tau",       r"$m_{\tilde{\nu}_{\tau}} %s$"%GeVc2 ),
        "squark_r"     : Var( "squark_r",      r"$m_{\tilde{q}_{r}} %s \textrm{(average)}$"%GeVc2 ),
        "squark_l"     : Var( "squark_l",      r"$m_{\tilde{q}_{l}} %s \textrm{(average)}$"%GeVc2 ),
        "stop1"        : Var( "stop1",         r"$m_{\tilde{t}_{1}} %s$"%GeVc2 ),
        "stop2"        : Var( "stop2",         r"$m_{\tilde{t}_{2}} %s$"%GeVc2 ),
        "sbottom1"     : Var( "sbottom1",      r"$m_{\tilde{b}_{1}} %s$"%GeVc2 ),
        "sbottom2"     : Var( "sbottom2",      r"$m_{\tilde{b}_{2}} %s$"%GeVc2 ),
        "gluino"       : Var( "gluino",        r"$m_{\tilde{g}} %s$"%GeVc2 ),
        "mh0"          : Var( "mh0",           r"$m_{h^{0}} %s$"%GeVc2 ),
        "mH0"          : Var( "mH0",           r"$m_{H^{0}} %s$"%GeVc2 ),
        "mA0"          : Var( "mA0",           r"$m_{A^{0}} %s$"%GeVc2 ),
        "mH+-"         : Var( "mH+-",          r"$m_{H^{\pm}} %s$"%GeVc2 ),  
    }
